"""empty message

Revision ID: 24b229ac9322
Revises: 
Create Date: 2023-06-09 22:27:59.301935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b229ac9322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('courseCode', sa.String(length=8), nullable=False),
    sa.Column('courseName', sa.String(length=100), nullable=True),
    sa.Column('creditHours', sa.Integer(), nullable=True),
    sa.Column('semestersOffered', sa.String(length=50), nullable=True),
    sa.Column('prerequisites', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('courseCode')
    )
    op.create_table('degrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty', sa.String(length=50), nullable=True),
    sa.Column('degreeName', sa.String(length=100), nullable=True),
    sa.Column('isOffered', sa.Boolean(), nullable=True),
    sa.Column('minNumOfCredits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('faculty', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('description',
    sa.Column('courseCode', sa.String(length=8), nullable=False),
    sa.Column('courseDescription', sa.String(length=5000), nullable=True),
    sa.Column('prerequisites', sa.String(length=100), nullable=True),
    sa.Column('corequisites', sa.String(length=100), nullable=True),
    sa.Column('antirequisites', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('courseCode')
    )
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty')
    )
    op.create_table('rating',
    sa.Column('courseCode', sa.String(length=8), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('courseCode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('faculties')
    op.drop_table('description')
    op.drop_table('department')
    op.drop_table('degrees')
    op.drop_table('courses')
    op.drop_table('accounts')
    # ### end Alembic commands ###
