"""empty message

Revision ID: 5cff8c05783b
Revises: 
Create Date: 2023-06-10 20:46:41.607531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cff8c05783b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('coursecode', sa.String(length=8), nullable=False),
    sa.Column('coursename', sa.String(length=100), nullable=True),
    sa.Column('credithours', sa.Integer(), nullable=True),
    sa.Column('semestersoffered', sa.String(length=50), nullable=True),
    sa.Column('prerequisites', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('coursecode')
    )
    op.create_table('degrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty', sa.String(length=50), nullable=True),
    sa.Column('degreename', sa.String(length=100), nullable=True),
    sa.Column('isoffered', sa.Boolean(), nullable=True),
    sa.Column('yearoffered', sa.Integer(), nullable=True),
    sa.Column('minnumofcredits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('faculty', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('description',
    sa.Column('coursecode', sa.String(length=8), nullable=False),
    sa.Column('coursedescription', sa.String(length=5000), nullable=True),
    sa.Column('prerequisites', sa.String(length=100), nullable=True),
    sa.Column('corequisites', sa.String(length=100), nullable=True),
    sa.Column('antirequisites', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('coursecode')
    )
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty')
    )
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qtype', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('coursecode', sa.String(length=8), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('coursecode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('qualifications')
    op.drop_table('faculties')
    op.drop_table('description')
    op.drop_table('department')
    op.drop_table('degrees')
    op.drop_table('courses')
    op.drop_table('accounts')
    # ### end Alembic commands ###
