"""empty message

Revision ID: b62673273536
Revises: cde4d0812cc9
Create Date: 2023-06-19 18:16:22.909722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62673273536'
down_revision = 'cde4d0812cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.String(length=8), nullable=True),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.Column('faculty', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('courses', sa.String(length=1000), nullable=True),
    sa.Column('grades', sa.String(length=500), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('desired_gpa', sa.Float(), nullable=True),
    sa.Column('exemptfrom', sa.String(length=300), nullable=True),
    sa.Column('qualifications', sa.String(length=1000), nullable=True),
    sa.Column('qualSubject', sa.String(length=3000), nullable=True),
    sa.Column('qualification_grades', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exclusivecourses')
    with op.batch_alter_table('degrees', schema=None) as batch_op:
        batch_op.drop_column('minnumofcredits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('degrees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minnumofcredits', sa.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('exclusivecourses',
    sa.Column('coursecode', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('coursename', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('credithours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('semestersoffered', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('prerequisites', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('restriction', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('coursecode', name='exclusivecourses_pkey')
    )
    op.drop_table('students')
    # ### end Alembic commands ###
