"""empty message

Revision ID: cde4d0812cc9
Revises: 5995e20cd9e9
Create Date: 2023-06-10 22:07:47.357880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde4d0812cc9'
down_revision = '5995e20cd9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusivecourses',
    sa.Column('coursecode', sa.String(length=8), nullable=False),
    sa.Column('coursename', sa.String(length=100), nullable=True),
    sa.Column('credithours', sa.Integer(), nullable=True),
    sa.Column('semestersoffered', sa.String(length=50), nullable=True),
    sa.Column('prerequisites', sa.String(length=300), nullable=True),
    sa.Column('restriction', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('coursecode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exclusivecourses')
    # ### end Alembic commands ###
